image: node:18

before_script:
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test:co

after_script:
  - echo 'after script here.'
